### PR TITLE
Allow the usage of unique faker data

### PR DESCRIPTION
**Pull request by acrobat**
This PR adds the ability to use the unique generator from the faker library. This allows to generate unique emails during the anonymisation

example:
```
...
entities:
    user_table:
        cols:
            email: { method: email, unique: true }
```

~~EDIT: Marked this pr as WIP as it seems that the fake data is not yet unique for the whole entity~~

### CODE REVIEW

**Comment by acrobat** [comment]
PR updated, I've cloned the faker object foreach entity column so it stays unique within a column

**Comment by edyan** [comment]
Hi @acrobat  and thanks for that, great idea. Can you add the unit tests ? Thanks !

**Comment by acrobat** [comment]
@edyan sure! Do you have an idea what a usefull test could be? Logic thing to check is if I specify `unique: true` that I have a different instance of the faker object. But the `getFakerObject` method is protected so only testable with a some dirty reflection "tricks".

**Comment by edyan** [comment]
Hi, reflection would be a good start to make sure it's working. But you can also try to generate many records and make sure the new value is always unique. I have done that for the uniqueWord method, coming from a dictionnary : https://github.com/edyan/neuralyzer/blob/master/tests/Faker/Provider/UniqueWordTest.php

Probably that email would create an issue. You can try with a `randomLetter`. Hope that helps :)

**Comment by acrobat** [comment]
@edyan I've added a unit test where I check the created faker object. I check if we generate an actual unique generator object and if two unique generators for different fields are different objects.

**Comment by edyan** [comment]
Hey @acrobat  just merged your modification. It's great ! I have only modified typehint of `getFakerObject` method. Also I have done a test with 10 000 000 records and it worked perfectly : 

```yaml
entities:
    guestbook:
        cols:
            username: { method: userName, unique: true }
            created: { method: date, params: [Y-m-d] }
            a_bigint: { method: randomNumber, params: [9] }
            a_datetime: { method: date, params: ['Y-m-d H:i:s'] }
            a_time: { method: time, params: ['H:i:s'] }
            a_decimal: { method: randomFloat, params: [2, 0, 999999] }
            an_integer: { method: randomNumber, params: [9] }
            a_smallint: { method: randomNumber, params: [4] }
            a_float: { method: randomFloat, params: [2, 0, 999999] }
        action: insert
        limit: 10000000
        pre_actions:
            - db.query("TRUNCATE guestbook")

guesser: Edyan\Neuralyzer\Guesser
guesser_version: '3.0'
language: en_US

```

If you have time one day, it would be great to have the following option in config, overriden by the CLI : 
```
  -D, --driver=DRIVER        Driver (check Doctrine documentation to have the list) [default: "pdo_mysql"]
  -H, --host=HOST            Host [default: "127.0.0.1"]
  -d, --db=DB                Database Name
  -u, --user=USER            User Name [default: "edyan"]
  -p, --password=PASSWORD    Password (or prompted)
```

**Comment by acrobat** [comment]
The exception you get can be "tweaked" by increasing the retry count on the [`UniqueGenerator`.](https://github.com/fzaninotto/Faker/blob/06ac73da6517f58afe998ed46f93825d7a277d8d/src/Faker/UniqueGenerator.php#L19). So maybe we can set default value higher when we initialize the object, something like 100k?

Ok, I will try to find some time to provide the config values for the connection info!

**Comment by edyan** [comment]
Not sure that would be a solution (to increase to 100k) : for each line to generate (7 Millions were remaining) we'll generate dozens of thousands of values. Won't that be slow ?

Else another solution : catch `\OverflowException` and insert what has been generated so far ?

**Comment by acrobat** [comment]
Catching the exception and writing the data and then continue with a "clean" faker object, won't really work as a solution because if a unique constraint applied on the db table itself, inserting the second batch might cause an db error.

Something that could work is, but the unique faker is not necessary anymore, to just generate a username forexample and then append the id of the row. That way we are always sure that value will be really unique. But then we should build another option into the neuralizer. What do you think?

**Comment by edyan** [comment]
I wasn't thinking of continuing with a clean faker object. I wanted more to say that if we don't catch the exception, the process will just stop as well as the anonymization. So it would be better to inject what has been generated so far instead of doing nothing. 

Also the uniqueness has also to be managed from the DB engine itself via an index. 

So keeping things as it is is a great idea below a certain number of records. Above, and to the Infinite (and beyond :)) , yes having a real unique record is a good idea. Two options for that : create a new faker type or have a more "powerful" method such as symfony expression language without making the system too complicated.

**Pull request merged**
